# Generated by Django 3.2.5 on 2021-07-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_category_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='categoryname',
        ),
    ]
