# Generated by Django 3.2.5 on 2021-07-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_name_category_categoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='release_status',
            field=models.BooleanField(default=True),
        ),
    ]
